### PR TITLE
Gcc 10 fix

### PR DESCRIPTION
**Pull request by bodqhrohro**

### CODE REVIEW

**Comment by bodqhrohro** [comment]
BTW, you forgot to update your name in READMEs of this project, purple-events and possibly other ones ;)

**Review by sardemff7 — APPROVED** [review]

**Review by sardemff7 — CHANGES_REQUESTED** [review]
I think it should be in a more global file, not duplicating Autotools stuff in every single repo

**Comment by bodqhrohro** [comment]
> I think it should be in a more global file, not duplicating Autotools stuff in every single repo

Hmm, does Git support submodules for certain files in a directory rather than for complete subdirectories?

**Comment by sardemff7** [comment]
I think the `.gitignore` stuff should be in a more global file, and not duplicated in every single repo using Autotools

> > I think it should be in a more global file, not duplicating Autotools stuff in every single repo
> 
> Hmm, does Git support submodules for certain files in a directory rather than for complete subdirectories?

Don’t think so, but what I though about was more on the “should be in people’s gitignore directly” side
The list of files isn’t really short, could change anytime if Autotools add/remove files (though unlikely, it happened already) and should not be a big bother for most people using the repo once

**Comment by sardemff7** [comment]
> Ah, about that… well, I'm a DRY fan too, but the world is not ideal xD
> 
> Actually, it wouldn't be a big problem if `make clean` removed all this mess properly (but this is prone to Autotools-side changes too).

Doesn’t `make distclean` work for that?

> Technically it would be a pretty sane idea to automatically provide some mixins for Git by Autotools. While things like editor-specific temporary files that mess up `.gitignore`s here and there too should better reside in the developer's personal `$XDG_CONFIG_HOME/git/ignore`, things related to the project toolchain should definitely go to the per-project `.gitignore`.

Sure, hence my `config.h` ignore line, but the rest are not limited to the “project” IMHO :-)


> From my experience with Nginx and ISPManager that tries to automatically patch Nginx configs, the approach of combining manual and automatic edits leads to irritating errors. Though there are many more successful examples, like `package.json` or `go.mod`, which survive the automatic edits jolly well. `.gitignore` has a flat structure, so just adding and removing lines shouldn't make much harm, I suppose. Still something like `.gitignore.d` would be better, but it also would break compatibility with old versions of Git.

Not a bad idea, it would be ignored (*pun intended*) by older Git anyway

> The other problem is that there are other version control systems out there, like Mercurial, and they have their own ignore files and possibly incompatible syntaxes. Should Autotools really take all of them into account and detect what VCS is being used?

Yes, Meson does (to some point) and it works, plus there aren’t that many “big” and FOSS VCS nowadays, so I’d say it’s not that big of a deal.

> A_nya_way, this discussion went a bit off-topic, so I'll better exclude the `.gitignore` change for now.

Thanks for putting up with my nitpicking :-D

**Comment by bodqhrohro** [comment]
> Doesn’t `make distclean` work for that?

Not quite, there are still lots of files remaining:

```
	.aux/
	Makefile.in
	aclocal.m4
	autom4te.cache/
	configure
	m4/
	po/Makefile.in.in
	src/config.h.in~
```

I raised a discussion in the Autotools mailing list, feel free to follow it: https://lists.gnu.org/archive/html/automake/2022-04/msg00006.html

**Comment by sardemff7** [comment]
There, now there is no need for a `.gitignore` any more :-)

**Pull request merged**
